plugins {
  id 'maven-publish'
  id 'com.enonic.defaults' version '2.1.7'
  id 'com.enonic.xp.app'
}

group = 'com.github.bouvet-apps'

dependencies {
    include xplibs.portal
}

repositories {
  mavenLocal()
  mavenCentral()
  xp.enonicRepo()
}

wrapper {
    gradleVersion = '9.5.0'
    distributionType = Wrapper.DistributionType.BIN
}